import {v4 as uuid} from 'uuid';

export interface Students {
    id: string
    courseCompletion: number
    courseEngagment: number
    projectDegree: number
    teamProjectDegree: number
    bonusProjectUrls: string
    tel: number
    firstName: string
    lastName: string
    githubUsername: string
    portfolioUrls: string
    projectUrls: string
    bio: string
    expectedContractType: string
    targetWorkCity: string
    expectedTypeWork: string
    expectedSalary: number
    canTakeApprenticeship: string
    monthsOfCommercialExp: number
    education: string
    workExperience: string
    courses: string
    reservationStatus: number
}

export const users: Students[] = [

    {
        id: uuid(),
        courseCompletion: 4,
        courseEngagment: 3,
        projectDegree: 2,
        teamProjectDegree: 4,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Adam',
        lastName: 'Kowalski',
        githubUsername: 'AdasK',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'B2B',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Praca zdalna',
        expectedSalary: 8900,
        canTakeApprenticeship: 'tak',
        monthsOfCommercialExp: 3,
        education: 'Liceum Ogólnokształcące',
        workExperience: 'e-ux.pro',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 0,
    },
    {
        id: uuid(),
        courseCompletion: 5,
        courseEngagment: 4,
        projectDegree: 4,
        teamProjectDegree: 5,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Katarzyna',
        lastName: 'Kowalska',
        githubUsername: 'KaskaK',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'Umowa zlecenie',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Biuro',
        expectedSalary: 4800,
        canTakeApprenticeship: 'nie',
        monthsOfCommercialExp: 12,
        education: 'Liceum Ogólnokształcące',
        workExperience: 'e-ux.pro',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 0,
    },
    {
        id: uuid(),
        courseCompletion: 3,
        courseEngagment: 1,
        projectDegree: 5,
        teamProjectDegree: 3,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Maciej',
        lastName: 'Maciejewski',
        githubUsername: 'MaciejMac',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'B2B',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Biuro',
        expectedSalary: 12000,
        canTakeApprenticeship: 'nie',
        monthsOfCommercialExp: 24,
        education: 'Liceum Ogólnokształcące',
        workExperience: 'e-ux.pro',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 0,
    },
    {
        id: uuid(),
        courseCompletion: 5,
        courseEngagment: 5,
        projectDegree: 5,
        teamProjectDegree: 5,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Alicja',
        lastName: 'Maciejewska',
        githubUsername: 'AlaMac',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'Umowa o dzieło',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Praca zdalna',
        expectedSalary: 3500,
        canTakeApprenticeship: 'tak',
        monthsOfCommercialExp: 0,
        education: 'Liceum Ogólnokształcące',
        workExperience: '',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 0,
    },
    {
        id: uuid(),
        courseCompletion: 4,
        courseEngagment: 3,
        projectDegree: 2,
        teamProjectDegree: 4,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Adam',
        lastName: 'Kowalski',
        githubUsername: 'AdasK',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'B2B',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Praca zdalna',
        expectedSalary: 8900,
        canTakeApprenticeship: 'tak',
        monthsOfCommercialExp: 3,
        education: 'Liceum Ogólnokształcące',
        workExperience: 'e-ux.pro',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 1,
    },
    {
        id: uuid(),
        courseCompletion: 5,
        courseEngagment: 4,
        projectDegree: 4,
        teamProjectDegree: 5,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Katarzyna',
        lastName: 'Kowalska',
        githubUsername: 'KaskaK',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'Umowa zlecenie',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Biuro',
        expectedSalary: 4800,
        canTakeApprenticeship: 'nie',
        monthsOfCommercialExp: 12,
        education: 'Liceum Ogólnokształcące',
        workExperience: 'e-ux.pro',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 1,
    },
    {
        id: uuid(),
        courseCompletion: 3,
        courseEngagment: 1,
        projectDegree: 5,
        teamProjectDegree: 3,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Maciej',
        lastName: 'Maciejewski',
        githubUsername: 'MaciejMac',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'B2B',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Biuro',
        expectedSalary: 12000,
        canTakeApprenticeship: 'nie',
        monthsOfCommercialExp: 24,
        education: 'Liceum Ogólnokształcące',
        workExperience: 'e-ux.pro',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 1,
    },
    {
        id: uuid(),
        courseCompletion: 5,
        courseEngagment: 5,
        projectDegree: 5,
        teamProjectDegree: 5,
        bonusProjectUrls: 'http://google.pl',
        tel: 333333333,
        firstName: 'Alicja',
        lastName: 'Maciejewska',
        githubUsername: 'AlaMac',
        portfolioUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        projectUrls: 'http://www.github.pl, http://www.udemy.pl, http://www.google.pl',
        bio: 'ja jestem bio',
        expectedContractType: 'Umowa o dzieło',
        targetWorkCity: 'Wrocław',
        expectedTypeWork: 'Praca zdalna',
        expectedSalary: 3500,
        canTakeApprenticeship: 'tak',
        monthsOfCommercialExp: 0,
        education: 'Liceum Ogólnokształcące',
        workExperience: '',
        courses: 'udemy, megak, ksiazki',
        reservationStatus: 0,
    },

]
